#!/bin/bash
set -euo pipefail

# mitmios Frontend Build Script
# Converts YAML tracker configs → TypeScript → Vite bundle

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIGS_DIR="$PROJECT_DIR/configs"
MITMPROXY_DIR="$PROJECT_DIR/mitmproxy"
OUTPUT_FILE="$MITMPROXY_DIR/web/src/js/trackers/configs.generated.ts"

echo "━━━ mitmios frontend build ━━━"
echo ""

# ── Step 1: Generate TypeScript from YAML configs ──

echo "[1/3] Generating tracker configs..."

if [ ! -d "$CONFIGS_DIR" ] || [ -z "$(ls -A "$CONFIGS_DIR"/*.yaml 2>/dev/null)" ]; then
    echo "  Warning: No YAML configs found in $CONFIGS_DIR"
    echo "  Generating empty configs.generated.ts"
    cat > "$OUTPUT_FILE" << 'TSEOF'
/**
 * Auto-generated by scripts/build-frontend.sh
 * No tracker configs found — add YAML files to configs/ and rebuild.
 */
import { TrackerConfig } from "./types";
export const trackerConfigs: TrackerConfig[] = [];
TSEOF
else
    python3 - "$CONFIGS_DIR" "$OUTPUT_FILE" << 'PYEOF'
import sys, os, json, glob, yaml

configs_dir = sys.argv[1]
output_file = sys.argv[2]

yaml_files = sorted(glob.glob(os.path.join(configs_dir, "*.yaml")))
print(f"  Found {len(yaml_files)} config(s):")

configs = []
required_fields = {"name", "description", "matchers", "display"}
required_matcher_fields = {"id", "label", "color", "host", "path_pattern"}

for yf in yaml_files:
    basename = os.path.basename(yf)
    try:
        with open(yf) as f:
            data = yaml.safe_load(f)

        # Validate required fields
        missing = required_fields - set(data.keys())
        if missing:
            print(f"  ERROR: {basename} missing fields: {missing}")
            sys.exit(1)

        # Validate matchers
        for i, m in enumerate(data.get("matchers", [])):
            m_missing = required_matcher_fields - set(m.keys())
            if m_missing:
                print(f"  ERROR: {basename} matcher[{i}] missing: {m_missing}")
                sys.exit(1)

        # Default extractors to empty list
        if "extractors" not in data:
            data["extractors"] = []

        configs.append(data)
        print(f"    {basename} -> {data['name']} ({len(data['matchers'])} matchers)")
    except yaml.YAMLError as e:
        print(f"  ERROR: Failed to parse {basename}: {e}")
        sys.exit(1)

# Generate TypeScript
lines = []
lines.append("/**")
lines.append(" * Auto-generated by scripts/build-frontend.sh")
lines.append(f" * Generated from {len(configs)} YAML config(s)")
lines.append(" * DO NOT EDIT — modify configs/*.yaml and rebuild instead.")
lines.append(" */")
lines.append('import { TrackerConfig } from "./types";')
lines.append("")

for i, cfg in enumerate(configs):
    var_name = f"config{i}"
    # Use JSON serialization then embed as TypeScript
    json_str = json.dumps(cfg, indent=4, ensure_ascii=False)
    lines.append(f"const {var_name}: TrackerConfig = {json_str};")
    lines.append("")

var_names = ", ".join(f"config{i}" for i in range(len(configs)))
lines.append(f"export const trackerConfigs: TrackerConfig[] = [{var_names}];")
lines.append("")

with open(output_file, "w") as f:
    f.write("\n".join(lines))

print(f"  Output: {os.path.basename(output_file)}")
PYEOF
fi

echo ""

# ── Step 2: Install npm dependencies (if needed) ──

echo "[2/3] Checking npm dependencies..."
cd "$MITMPROXY_DIR/web"
if [ ! -d "node_modules" ]; then
    echo "  Installing dependencies..."
    npm ci
else
    echo "  Dependencies already installed"
fi

echo ""

# ── Step 3: Build frontend ──

echo "[3/3] Building frontend..."
npm run ci-build-release 2>&1

echo ""
echo "━━━ Build complete ━━━"
echo "Output: $MITMPROXY_DIR/web/built/"
